# =============================================================================
# INCLUDE TEMPLATES
# =============================================================================

include:
  - project: "trulysystems/msp/devops/pipeline"
    file: "/bronze.yml"

# =============================================================================
# GLOBAL VARIABLES
# =============================================================================